services:

  #PHP Service
  ogame-app:
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPCACHE_ENABLE: "0"  # Disable opcache for development
        USE_USER: ${USE_USER_ARG:-yes}  # Defaults to "yes". Set to "no" for GitHub Actions.
    image: digitalocean.com/php
    container_name: ogame-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  ogame-webserver:
    image: nginx:alpine
    container_name: ogame-webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #MariaDB Service
  ogame-db:
    image: mariadb:11.3.2-jammy
    container_name: ogame-db
    restart: unless-stopped
    tty: true
    volumes:
     - ogame-dbdata:/var/lib/mysql
     - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: toor
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  ogame-dbdata:
    driver: local
