services:

  # MariaDB Service
  ogamex-db:
    image: mariadb:11.3.2-jammy
    container_name: ogamex-db
    restart: unless-stopped
    tty: true
    volumes:
     - ogame-dbdata:/var/lib/mysql
     - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_ROOT_PASSWORD: toor
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 6s
      retries: 60
    networks:
      app-network:
        aliases:
          - ogame-db

  # PHP Service
  ogamex-app:
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/var/www
      # Do not volume mount build directories
      - /var/www/bootstrap/cache
      - /var/www/vendor
      - /var/www/rust
      - /var/www/storage/rust-libs
    image: ogamex/app
    build:
      context: .
      dockerfile: Dockerfile
      target: app_dev
      args:
        OPCACHE_ENABLE: "0"  # Disable opcache for development
        USE_USER: ${USE_USER_ARG:-yes}  # Defaults to "yes". Set to "no" for GitHub Actions.
    container_name: ogamex-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || [ $? -eq 56 ]"]
      interval: 10s
      timeout: 6s
      retries: 60
    networks:
      - app-network
    depends_on:
      ogamex-db:
        condition: service_healthy

  # Scheduler
  ogamex-scheduler:
    image: ogamex/scheduler
    build:
      context: .
      dockerfile: Dockerfile
      target: scheduler
    container_name: ogamex-scheduler
    restart: unless-stopped
    volumes:
      - ./:/var/www
      # Do not volume mount build directories
      - /var/www/bootstrap/cache
      - /var/www/vendor
      - /var/www/rust
      - /var/www/storage/rust-libs
    networks:
      - app-network
    depends_on:
      ogamex-app:
        condition: service_healthy

  # Queue
  ogamex-queue-worker:
    image: ogamex/queue-worker
    build:
      context: .
      dockerfile: Dockerfile
      target: queue
    container_name: ogamex-queue-worker
    restart: unless-stopped
    volumes:
      - ./:/var/www
      # Do not volume mount build directories
      - /var/www/bootstrap/cache
      - /var/www/vendor
      - /var/www/rust
      - /var/www/storage/rust-libs
    networks:
      - app-network
    depends_on:
      ogamex-app:
        condition: service_healthy

  # Nginx Service
  ogamex-webserver:
    image: nginx:alpine
    container_name: ogamex-webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      ogamex-app:
        condition: service_healthy

  # PhpMyAdmin
  ogamex-phpmyadmin:
    image: phpmyadmin
    container_name: ogamex-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=ogame-db
      - UPLOAD_LIMIT=1G
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  ogame-dbdata:
    driver: local
