name: Docker Compose Unit Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'resources/css/**'
      - 'resources/js/**'
      - 'public/css/**'
      - 'public/js/**'
      - 'public/mix-manifest.json'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'webpack.mix.js'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'resources/css/**'
      - 'resources/js/**'
      - 'public/css/**'
      - 'public/js/**'
      - 'public/mix-manifest.json'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'webpack.mix.js'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:26.0.0
        options: --privileged
    steps:
      - uses: actions/checkout@v6

      - name: Setup Docker Compose
        uses: ./.github/actions/docker-compose-setup

      - name: Run Tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: docker compose exec -T ogamex-app php artisan test

      - name: Run custom Race Condition Tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker compose exec -T ogamex-app php artisan ogamex:test:race-condition-unitqueue
            docker compose exec -T ogamex-app php artisan ogamex:test:race-condition-game-mission
            docker compose exec -T ogamex-app php artisan ogamex:test:race-condition-fleet-dispatch
            docker compose exec -T ogamex-app php artisan ogamex:test:race-condition-unitqueue-creation
